import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
// import Navbar from "./components/Navbar";
// import Footer from "@/app/components/Footer";
const inter = Inter({ subsets: ["latin"] });
// import 'tailwindcss/tailwind.css';

export const metadata: Metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`body ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
